### PR TITLE
Fincrypchain (FCC)

### PR DESCRIPTION
**Pull request by fincrypchain-io**
https://etherscan.io/address/0x611c74310a06b10593e073affe4ea543b793f539
0x611c74310a06B10593E073aFFe4Ea543b793f539

### CODE REVIEW

**Comment by tranvictor** [comment]
hi @fincrypchain-io, can you please explain the intention of the PR?

**Comment by fincrypchain-io** [comment]
PR is shot form for ?

**Comment by fincrypchain-io** [comment]
The Fincrypchain Token (symbol: FCC ) will be used as currency within our
platform, and will therefore be used for donations, purchases. Using the
Ethereum blockchain our community will be able to receive payments safely
and quickly, thus eliminating the annoying problems and slowness of the fiat
currencies.
Fincrypchain ( FCC ) token is a long term project, all our calculations have been
made in order to guarantee an
“uninterrupted” production flow, (all this regardless of the various market
fluctuations). Our token will be essential for:
• Making a donation
• Purchasing a song
• Royalty Payouts
It will be used as means of payment on the cryptology research system.

**Comment by tranvictor** [comment]
hi @fincrypchain-io, so it looks like you want your token to be listed on KyberSwap? If so, this is not where to do it, I appreciate your effort to make a PR though.
Please reach out to our listing officer on telegram at @NaqibNoor to learn more about the listing process.

I will close this PR now.

**Pull request closed without merging**
